Add README.
perun-network/perun-eth-payment pull request #2
Opened 2021-03-15 11:41 UTC by ggwpez

2021-04-12 16:46 UTC, ggwpez commented
The import path is not yet working, but you can still take a look.  
You can obviously also make additions if you want. @matthiasgeihs

2021-04-12 16:48 UTC, ggwpez commented on README.md
> +  <a href="https://pkg.go.dev/perun.network/go-perun?status.svg"> <img src="https://img.shields.io/badge/go.dev-reference-007d9c?logo=go&logoColor=white" alt="pkg.go.dev docs"></a>
I will fix this once @tinnendo got the path running.

2021-04-13 14:42 UTC, matthiasgeihs requested changes
Minor corrections wrt language

2021-04-13 14:42 UTC, matthiasgeihs commented on README.md
> +This project provides a simplified interfaec of the [*go-perun*](https://github.com/hyperledger-labs/go-perun) framework. It enables developers to get started quickly with *go-perun* by using a conde
typo: interfaec -> interface

2021-04-13 14:42 UTC, matthiasgeihs commented on README.md
> +If you just want to create a *go-perun* payment on Ethereum, this is for you.
Create a go-perun payment? You mean create a payment application?

2021-04-14 09:52 UTC, matthiasgeihs commented on README.md
> +This project provides a simplified interface of the [*go-perun*](https://github.com/hyperledger-labs/go-perun) framework. It enables developers to get started quickly with *go-perun* by using a conde
Interface "to"

2021-04-14 09:54 UTC, matthiasgeihs reviewed
I think we can use the github path. What do you think?

2021-04-14 10:03 UTC, ggwpez commented
> I think we can use the github path. What do you think?

Yes right… Did not even think about this anymore :see_no_evil:  
I will remove the commit and change the `README` to just use `github.com/perun-network/perun-eth-payment`.

2021-04-14 12:35 UTC, matthiasgeihs approved these changes

2021-04-14 12:35 UTC, merged